# Generated by Django 4.2.4 on 2023-09-04 07:01

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='E',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('eid', models.CharField(max_length=20)),
                ('ename', models.CharField(max_length=20)),
                ('econtact', models.CharField(max_length=20)),
            ],
            options={
                'db_table': 'Emp',
            },
        ),
    ]
